
const desafios = [
  {
    id: 1,
    id_fase: 1,
    texto_fase: [
      'Bem-vindo ao seu primeiro desafio de Python!',
      ' Em Python, para mostrar uma mensagem na tela, usamos a função print(). Ela é uma das funções mais usadas na linguagem e é perfeita para exibir textos, números e resultados.',
      'Exemplo:',
      '  print("Olá, mundo!")',
      'Isso vai exibir no terminal:',
      '  Olá, mundo!',
      'Agora é a sua vez! Observe o código abaixo:',
      '  print("Eu estou aprendendo Python!")',
      'O que esse código vai exibir na tela quando for executado?',
    ],
    alternativas: [
      { id: "A", texto: 'Eu estou aprendendo Python!' },
      { id: "B", texto: 'print("Eu estou aprendendo Python!")' },
      { id: "C", texto: 'Erro, falta ponto e vírgula no final' },
      { id: "D", texto: 'Nada, o código está errado' },
    ],
    correta: "A",
    se_errar: 'Quase lá! Lembre-se que a função print() exibe apenas o conteúdo que está dentro das aspas, sem mostrar a função em si. Tente novamente!',
    se_acertar: 'Parabéns! Você acertou! 🎉',
  },
  {
    id: 2,
    id_fase: 1,
    texto_fase: [
      '🐍 Agora vamos falar sobre variáveis!',
      'Uma variável é como uma caixinha onde você guarda um valor para usar depois. Em Python, criar uma variável é muito simples — basta escolher um nome e atribuir um valor usando o sinal de igual (=).',
      'Exemplo:',
      '  nome = "Maria"',
      '  print(nome)',
      'Isso vai exibir:',
      '  Maria',
      'Observe o código abaixo:',
      '  idade = 25',
      '  print(idade)',
      'O que será exibido na tela quando esse código for executado?',
    ],
    alternativas: [
      { id: "A", texto: '"idade"' },
      { id: "B", texto: 'idade = 25' },
      { id: "C", texto: '25' },
      { id: "D", texto: 'Erro, números não podem ser guardados em variáveis' },
    ],
    correta: "C",
    se_errar: 'Atenção! Quando usamos print() com o nome de uma variável (sem aspas), o Python exibe o valor guardado nela, não o nome. Tente novamente!',
    se_acertar: 'Parabéns! Você acertou! 🎉',
  },
  {
    id: 3,
    id_fase: 1,
    texto_fase: [
      '🐍 Hora de aprender sobre tipos de dados!',
      'Em Python, existem diferentes tipos de dados. Os mais comuns para iniciantes são:',
      '• String (str): textos, sempre entre aspas. Ex: "olá"',
      '• Inteiro (int): números sem casas decimais. Ex: 10',
      '• Float: números com casas decimais. Ex: 3.14',
      '• Booleano (bool): verdadeiro ou falso. Ex: True ou False',
      'Observe as variáveis abaixo:',
      '  a = "Python"',
      '  b = 42',
      '  c = 3.14',
      '  d = True',
      'Qual dessas variáveis é do tipo String (str)?',
    ],
    alternativas: [
      { id: "A", texto: 'b' },
      { id: "B", texto: 'c' },
      { id: "C", texto: 'd' },
      { id: "D", texto: 'a' },
    ],
    correta: "D",
    se_errar: "Quase! Strings são textos que ficam entre aspas (\" \" ou ' '). Olhe novamente para as variáveis e veja qual delas tem um texto entre aspas.",
    se_acertar: 'Parabéns! Você acertou! 🎉',
  },
  {
    id: 4,
    id_fase: 1,
    texto_fase: [
      '🐍 Vamos praticar operações matemáticas!',
      'Python pode funcionar como uma calculadora poderosa. Os operadores matemáticos básicos são:',
      '  +  →  soma',
      '  -  →  subtração',
      '  *  →  multiplicação',
      '  /  →  divisão',
      'Exemplo:',
      '  resultado = 10 + 5',
      '  print(resultado)',
      'Isso exibe: 15',
      'Agora observe o código abaixo:',
      '  x = 8',
      '  y = 3',
      '  print(x * y)',
      'Qual será o resultado exibido na tela?',
    ],
    alternativas: [
      { id: "A", texto: '83' },
      { id: "B", texto: '11' },
      { id: "C", texto: '24' },
      { id: "D", texto: '5' },
    ],
    correta: "C",
    se_errar: 'Atenção! O operador * em Python representa multiplicação, não concatenação. Então 8 * 3 significa 8 vezes 3. Tente calcular novamente!',
    se_acertar: 'Parabéns! Você acertou! 🎉',
  },
  {
    id: 5,
    id_fase: 1,
    texto_fase: [
      '🐍 Desafio final da fase 1: entrada de dados com input()!',
      'Além de exibir informações com print(), o Python também consegue receber informações do usuário usando a função input(). Ela pausa o programa e espera que o usuário digite algo.',
      'Exemplo:',
      '  nome = input("Qual é o seu nome? ")',
      '  print("Olá, " + nome + "!")',
      'Se o usuário digitar "Carlos", o programa exibirá:',
      '  Olá, Carlos!',
      'Agora observe o código abaixo:',
      '  linguagem = input("Qual linguagem você está aprendendo? ")',
      '  print("Você está aprendendo " + linguagem)',
      'Se o usuário digitar "Python", o que será exibido na tela?',
    ],
    alternativas: [
      { id: "A", texto: 'Você está aprendendo linguagem' },
      { id: "B", texto: 'Você está aprendendo "Python"' },
      { id: "C", texto: 'Você está aprendendo Python' },
      { id: "D", texto: 'Erro, não é possível juntar textos com o operador +' },
    ],
    correta: "C",
    se_errar: 'Quase lá! O operador + entre strings serve para juntá-las (concatenação). O valor que o usuário digitou é guardado na variável sem as aspas. Tente novamente!',
    se_acertar: 'Parabéns! Você acertou! 🎉',
  },
];

export default desafios;